### ISSUE TITLE
Redundant type decalration

### ISSUE THREAD

**Issue by Ron537** [blue-stream/blue-stream-comments#2]
https://github.com/blue-stream/blue-stream-comments/blob/4b6080f6a9b04dd8a482e0b79e4c037286875311/src/comment/validator/comment.validator.config.ts#L1-L6

No need to create a type if you only use it once to export an object.
Typescript will automatically know the type once you assign values to the object you export.

**Comment by AlmogVC** [comment]
I shall combine this config file with the main one (And solve this issue in the process).
