### ISSUE TITLE
Identify user via the jwt token

### ISSUE THREAD

**Issue by saarmornel** [blue-stream/blue-stream-comments#9]
I don't see why the http request should consist the user id, i think it should be automatic extract from the JWT token.
It also doesn't seem to  be secure this way, because one person can post using another user id.
I think you should use the utility we've done for JWT.

The same question apply for the Reaction Microservice.

**Comment by Ron537** [comment]
The user encrypted in the `jwt` can be accessed via `req.user` as long as the `auth.required` flag is checked in the configuration file.

**Comment by saarmornel** [comment]
of course it is...this is not the question. if you look at the code, you see that you have to provide manually the userid in the req.body, and that's the issue.

**Comment by AlmogVC** [comment]
Security, identification and permissions were not discussed yet at the creation of this service, and have not been discussed fully until now.
No changes will be made to the way the user is received until a full workflow will be conceived.

The way the compositor and the identifier will be implemented can change the way we implement the extraction of the user id.

This issue will be closed until we finish planing the full workflow
